export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_SHOPPING_BAG = "ADD_TO_SHOPPING_BAG";
export const ADD_MULTIPLE_TO_SHOPPING_BAG = "ADD_MULTIPLE_TO_SHOPPING_BAG";
export const REMOVE_FROM_SHOPPING_BAG = "REMOVE_FROM_SHOPPING_BAG";
export const CLEAR_SHOPPING_BAG = "CLEAR_SHOPPING_BAG";
export const UPDATE_SHOPPING_BAG_QUANTITY = "UPDATE_SHOPPING_BAG_QUANTITY";
export const TOGGLE_SHOPPING_BAG = "TOGGLE_SHOPPING_BAG";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";

export const UPDATE_DESIGNERS = "UPDATE_DESIGNERS";
export const UPDATE_CURRENT_DESIGNER = "UPDATE_CURRENT_DESIGNER";

export const UPDATE_COLORS = "UPDATE_COLORS";
export const UPDATE_CURRENT_COLOR = "UPDATE_CURRENT_COLOR";