const db = require('../config/connection');
const { User, Product, Category, Color, Designer } = require('../models');

db.once('open', async () => {
    try {
        await Color.deleteMany({});

        const colors = await Color.insertMany([
            // colors[0]._id
            { name: "Beige" },
            // colors[1]._id
            { name: "Black" },
            // colors[2]._id
            { name: "Blue" },
            // colors[3]._id
            { name: "Brown" },
            // colors[4]._id
            { name: "Gold" },
            // colors[5]._id
            { name: "Gray" },
            // colors[6]._id
            { name: "Green" },
            // colors[7]._id
            { name: "Orange" },
            // colors[8]._id
            { name: "Pink" },
            // colors[9]._id
            { name: "Purple" },
            // colors[10]._id
            { name: "Red" },
            // colors[11]._id
            { name: "Silver" },
            // colors[12]._id
            { name: "White" },
            // colors[13]._id
            { name: "Yellow" },
            // colors[14]._id
            { name: "Multi" },
            // colors[15]._id,
            { name: "None" }
        ])

        console.log('colors seeded');

        await Designer.deleteMany({});

        const designers = await Designer.insertMany([
            { name: "AESOP" },
            { name: "ALANUI" },
            { name: "ALEXANDER WANG" },
            { name: "ANISSA KERMICHE" },
            { name: "ANITA KO" },
            { name: "ANYA HINDMARCH" },
            { name: "AP8" },
            { name: "BRUNELLO CUCINELLI" },
            { name: "BYREDO" },
            { name: "CARTIER" },
            { name: "CHLOÉ" },
            { name: "CHOPARD" },
            { name: "CHRISTIAN DIOR" },
            { name: "DIOR" },
            { name: "DIPTYQUE" },
            { name: "DRIES VAN NOTEN" },
            { name: "FOUNDRAE" },
            { name: "GIVENCHY" },
            { name: "GUCCI" },
            { name: "HERMES" },
            { name: "HOURGLASS" },
            { name: "IRENE NEUWIRTH" },
            { name: "JIMMY CHOO" },
            { name: "JO MALONE" },
            { name: "LA DOUBLEJ" },
            { name: "LA MER" },
            { name: "LA PRAIRIE" },
            { name: "L'OBJETTerra" },
            { name: "LOEWE" },
            { name: "LOEWE HOME SCENTS" },
            { name: "MZ SKIN" },
            { name: "OSCAR DE LA RENTA" },
            { name: "POMELLATO" },
            { name: "PRADA" },
            { name: "SAINT LAURENT" },
            { name: "SLIP" },
            { name: "STORIES OF ITALY" },
            { name: "SYDNEY EVAN" },
            { name: "THE ROW" },
            { name: "THOM BROWNE" },
            { name: "TOM FORD" },
            { name: "VALENTINO" },
        ])

        console.log('designers seeded');

        await Category.deleteMany({});

        const categories = await Category.insertMany([
            {
                name: "bags"
            },
            {
                name: "beauty"
            },
            {
                name: "clothing"
            },
            {
                name: "home"
            },
            {
                name: "jewelry-and-accessories"
            },
            {
                name: "shoes"
            }
        ])

        console.log('categories seeded');

        await Product.deleteMany({});

        const products = await Product.insertMany([
            {
                image: "01",
                designer: designers[12]._id,
                category: categories[0]._id,
                name: "Caro shoulder bag",
                price: 3000,
                color: colors[0]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-02-29T00:22:53.902Z",
                updatedAt: "2022-02-29T00:22:53.902Z",
            },
            {
                image: "02",
                designer: designers[12]._id,
                category: categories[0]._id,
                name: "Lady-d-Light tote bag",
                price: 4500,
                color: colors[0]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-02-29T00:22:53.902Z",
                updatedAt: "2023-02-29T00:22:53.902Z",
            },
            {
                image: "03",
                designer: designers[12]._id,
                category: categories[0]._id,
                name: "Small lady",
                price: 5600,
                color: colors[0]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-02-29T00:22:53.902Z",
                updatedAt: "2023-03-29T00:22:53.902Z",
            },
            {
                image: "04",
                designer: designers[19]._id,
                category: categories[0]._id,
                name: "Roulis",
                price: 6000,
                color: colors[1]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-03-29T00:22:53.902Z",
                updatedAt: "2023-04-29T00:22:53.902Z",
            },
            {
                image: "05",
                designer: designers[19]._id,
                category: categories[0]._id,
                name: "Wave",
                price: 2500,
                color: colors[1]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-04-29T00:22:53.902Z",
                updatedAt: "2023-05-29T00:22:53.902Z",
            },
            {
                image: "06",
                designer: designers[19]._id,
                category: categories[0]._id,
                name: "Birkin",
                price: 20000,
                color: colors[1]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-05-29T00:22:53.902Z",
                updatedAt: "2023-06-29T00:22:53.902Z",
            },
            {
                image: "07",
                designer: designers[33]._id,
                category: categories[0]._id,
                name: "Kristen",
                price: 3600,
                color: colors[1]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-06-29T00:22:53.902Z",
                updatedAt: "2023-07-29T00:22:53.902Z",
            },
            {
                image: "08",
                designer: designers[33]._id,
                category: categories[0]._id,
                name: "Re-edition 2005 saffiano",
                price: 2550,
                color: colors[1]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-07-29T00:22:53.902Z",
                updatedAt: "2023-08-29T00:22:53.902Z",
            },
            {
                image: "09",
                designer: designers[33]._id,
                category: categories[0]._id,
                name: "Symbole",
                price: 2550,
                color: colors[1]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-08-29T00:22:53.902Z",
                updatedAt: "2023-09-29T00:22:53.902Z",
            },
            {
                image: "10",
                designer: designers[39]._id,
                category: categories[0]._id,
                name: "Mini hector",
                price: 2215,
                color: colors[1]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-09-29T00:22:53.902Z",
                updatedAt: "2023-10-29T00:22:53.902Z",
            },
            {
                image: "01",
                designer: designers[7]._id,
                category: categories[2]._id,
                name: "Bead-embellished shearling-lined leather jacket",
                price: 1200,
                color: colors[3]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-12-27T00:22:53.902Z",
                updatedAt: "2023-12-27T00:22:53.902Z",
            },
            {
                image: "02",
                designer: designers[10]._id,
                category: categories[2]._id,
                name: "Belted shearling vest",
                price: 900,
                color: colors[3]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2029-02-27T00:22:53.902Z",
                updatedAt: "2022-02-27T00:22:53.902Z",
            },
            {
                image: "03",
                designer: designers[10]._id,
                category: categories[2]._id,
                name: "Fringed macramé leather midi dress",
                price: 1400,
                color: colors[10]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-05-27T00:22:53.902Z",
                updatedAt: "2022-05-27T00:22:53.902Z",
            },
            {
                image: "04",
                designer: designers[17]._id,
                category: categories[2]._id,
                name: "Embellished crepe midi dress",
                price: 1650,
                color: colors[6]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-05-26T00:22:53.902Z",
                updatedAt: "2022-05-26T00:22:53.902Z",
            },
            {
                image: "05",
                designer: designers[31]._id,
                category: categories[2]._id,
                name: "Strapless appliquéd shell mini dress",
                price: 2300,
                color: colors[4]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-07-27T00:22:53.902Z",
                updatedAt: "2022-07-27T00:22:53.902Z",
            },
            {
                image: "06",
                designer: designers[34]._id,
                category: categories[2]._id,
                name: "Faux fur coat",
                price: 3999,
                color: colors[4]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-03-27T00:22:53.902Z",
                updatedAt: "2022-03-27T00:22:53.902Z",
            },
            {
                image: "07",
                designer: designers[38]._id,
                category: categories[2]._id,
                name: "Agathon belted quilted leather coat",
                price: 2699,
                color: colors[4]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-09-13T00:22:53.902Z",
                updatedAt: "2022-09-16T00:22:53.902Z",
            },
            {
                image: "08",
                designer: designers[40]._id,
                category: categories[2]._id,
                name: "Strapless silk gown",
                price: 1599,
                color: colors[4]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-10-12T00:22:53.902Z",
                updatedAt: "2022-10-12T00:22:53.902Z",
            },
            {
                image: "09",
                designer: designers[41]._id,
                category: categories[2]._id,
                name: "Cutout crystal-embellished silk-cady gown",
                price: 4500,
                color: colors[4]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-02-17T00:22:53.902Z",
                updatedAt: "2022-02-17T00:22:53.902Z",
            },
            {
                image: "10",
                designer: designers[41]._id,
                category: categories[2]._id,
                name: "Sequined tulle maxi skirt",
                price: 2500,
                color: colors[4]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-08-16T00:22:53.902Z",
                updatedAt: "2022-08-16T00:22:53.902Z",
            },
            {
                image: "11",
                designer: designers[1]._id,
                category: categories[3]._id,
                name: "Explosion Nature fringed cotton-blend jacquard blanket",
                price: 1500,
                color: colors[5]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-01-22T00:22:53.902Z",
                updatedAt: "2023-01-22T00:22:53.902Z",
            },
            {
                image: "12",
                designer: designers[3]._id,
                category: categories[3]._id,
                name: "Vase",
                price: 400,
                color: colors[5]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-02-11T00:22:53.902Z",
                updatedAt: "2023-02-11T00:22:53.902Z",
            },
            {
                image: "13",
                designer: designers[5]._id,
                category: categories[3]._id,
                name: "Eyes textured-leather watch box",
                price: 600,
                color: colors[6]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-02-27T00:22:53.902Z",
                updatedAt: "2022-02-27T00:22:53.902Z",
            },
            {
                image: "14",
                designer: designers[6]._id,
                category: categories[3]._id,
                name: "Guy Bourdin framed print",
                price: 900,
                color: colors[6]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-04-29T00:22:53.902Z",
                updatedAt: "2022-04-29T00:22:53.902Z",
            },
            {
                image: "15",
                designer: designers[7]._id,
                category: categories[3]._id,
                name: "Fringed cashmere travel blanket",
                price: 1500,
                color: colors[6]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-07-27T00:22:53.902Z",
                updatedAt: "2022-07-27T00:22:53.902Z",
            },
            {
                image: "16",
                designer: designers[7]._id,
                category: categories[3]._id,
                name: "Set of three stone plates",
                price: 300,
                color: colors[6]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-03-27T00:22:53.902Z",
                updatedAt: "2022-03-27T00:22:53.902Z",
            },
            {
                image: "17",
                designer: designers[27]._id,
                category: categories[3]._id,
                name: "Medium porcelain bowl",
                price: 650,
                color: colors[3]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-09-13T00:22:53.902Z",
                updatedAt: "2022-09-16T00:22:53.902Z",
            },
            {
                image: "18",
                designer: designers[24]._id,
                category: categories[3]._id,
                name: "Set of six gold-plated porcelain dessert plates",
                price: 600,
                color: colors[15]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-10-12T00:22:53.902Z",
                updatedAt: "2022-10-12T00:22:53.902Z",
            },
            {
                image: "19",
                designer: designers[29]._id,
                category: categories[3]._id,
                name: "Cucumber large scented candle, 2120g",
                price: 150,
                color: colors[15]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-02-17T00:22:53.902Z",
                updatedAt: "2022-02-17T00:22:53.902Z",
            },
            {
                image: "20",
                designer: designers[36]._id,
                category: categories[3]._id,
                name: "Macchia su Macchia set of six Murano glass tumblers",
                price: 200,
                color: colors[15]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-08-16T00:22:53.902Z",
                updatedAt: "2022-08-16T00:22:53.902Z",
            },
            {
                image: "21",
                designer: designers[4]._id,
                category: categories[4]._id,
                name: "18-karat gold, diamond and emerald necklace",
                price: 45000,
                color: colors[15]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-01-22T00:22:53.902Z",
                updatedAt: "2023-01-22T00:22:53.902Z",
            },
            {
                image: "22",
                designer: designers[9]._id,
                category: categories[4]._id,
                name: "Tank Française 32mm medium 18-karat gold diamond watch",
                price: 26000,
                color: colors[15]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-02-11T00:22:53.902Z",
                updatedAt: "2023-02-11T00:22:53.902Z",
            },
            {
                image: "23",
                designer: designers[11]._id,
                category: categories[4]._id,
                name: "Happy Sport Automatic 33mm 18-karat rose gold, stainless steel and diamond watch",
                price: 13500,
                color: colors[15]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-02-27T00:22:53.902Z",
                updatedAt: "2022-02-27T00:22:53.902Z",
            },
            {
                image: "24",
                designer: designers[15]._id,
                category: categories[4]._id,
                name: "Silver-tone, crystal and glass earrings",
                price: 535,
                color: colors[15]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-04-29T00:22:53.902Z",
                updatedAt: "2022-04-29T00:22:53.902Z",
            },
            {
                image: "25",
                designer: designers[16]._id,
                category: categories[4]._id,
                name: "Oversized Strong Hearts 18-karat gold necklace",
                price: 1650,
                color: colors[15]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-07-27T00:22:53.902Z",
                updatedAt: "2022-07-27T00:22:53.902Z",
            },
            {
                image: "26",
                designer: designers[18]._id,
                category: categories[4]._id,
                name: "Gold-tone and crystal earrings",
                price: 1300,
                color: colors[15]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-03-27T00:22:53.902Z",
                updatedAt: "2022-03-27T00:22:53.902Z",
            },
            {
                image: "27",
                designer: designers[21]._id,
                category: categories[4]._id,
                name: "Swing Hoops 18-karat yellow and white gold, turquoise and diamond earrings",
                price: 11999,
                color: colors[10]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-09-13T00:22:53.902Z",
                updatedAt: "2022-09-16T00:22:53.902Z",
            },
            {
                image: "28",
                designer: designers[28]._id,
                category: categories[4]._id,
                name: "Gold-tone brooch",
                price: 500,
                color: colors[4]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-10-12T00:22:53.902Z",
                updatedAt: "2022-10-12T00:22:53.902Z",
            },
            {
                image: "29",
                designer: designers[32]._id,
                category: categories[4]._id,
                name: "Nudo 18-karat rose gold, diamond and topaz cuff",
                price: 4500,
                color: colors[0]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-02-17T00:22:53.902Z",
                updatedAt: "2022-02-17T00:22:53.902Z",
            },
            {
                image: "30",
                designer: designers[37]._id,
                category: categories[4]._id,
                name: "14-karat gold, emerald and diamond hoop earrings",
                price: 4500,
                color: colors[11]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-08-16T00:22:53.902Z",
                updatedAt: "2022-08-16T00:22:53.902Z",
            },
            {
                image: "01",
                designer: designers[0]._id,
                category: categories[1]._id,
                name: "Resurrection aromatique hand wash",
                price: 41,
                color: colors[11]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-02-29T00:22:53.902Z",
                updatedAt: "2022-03-29T00:22:53.902Z",
            },
            {
                image: "02",
                designer: designers[0]._id,
                category: categories[1]._id,
                name: "Cellreturn platinum led face mask",
                price: 2100,
                color: colors[6]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-03-29T00:22:53.902Z",
                updatedAt: "2022-04-29T00:22:53.902Z",
            },
            {
                image: "03",
                designer: designers[8]._id,
                category: categories[1]._id,
                name: "Young rose",
                price: 290,
                color: colors[3]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-04-29T00:22:53.902Z",
                updatedAt: "2022-05-29T00:22:53.902Z",
            },
            {
                image: "04",
                designer: designers[14]._id,
                category: categories[1]._id,
                name: "Tuberose",
                price: 190,
                color: colors[14]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-05-29T00:22:53.902Z",
                updatedAt: "2022-06-29T00:22:53.902Z",
            },
            {
                image: "05",
                designer: designers[20]._id,
                category: categories[1]._id,
                name: "Vegan travel brush set",
                price: 320,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-06-29T00:22:53.902Z",
                updatedAt: "2022-07-29T00:22:53.902Z",
            },
            {
                image: "06",
                designer: designers[23]._id,
                category: categories[1]._id,
                name: "English pear & freesia",
                price: 75,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-07-29T00:22:53.902Z",
                updatedAt: "2022-08-29T00:22:53.902Z",
            },
            {
                image: "07",
                designer: designers[25]._id,
                category: categories[1]._id,
                name: "The moisturizing soft cream",
                price: 380,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-08-29T00:22:53.902Z",
                updatedAt: "2022-09-29T00:22:53.902Z",
            },
            {
                image: "08",
                designer: designers[26]._id,
                category: categories[1]._id,
                name: "Platinum rare cellular night elixir",
                price: 1460,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-09-29T00:22:53.902Z",
                updatedAt: "2022-10-29T00:22:53.902Z",
            },
            {
                image: "09",
                designer: designers[30]._id,
                category: categories[1]._id,
                name: "Hydro-bright gold eye mask",
                price: 105,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-10-29T00:22:53.902Z",
                updatedAt: "2022-11-29T00:22:53.902Z",
            },
            {
                image: "10",
                designer: designers[35]._id,
                category: categories[1]._id,
                name: "Silk Pillowcase",
                price: 89,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-11-29T00:22:53.902Z",
                updatedAt: "2022-12-29T00:22:53.902Z",
            },
            {
                image: "01",
                designer: designers[19]._id,
                category: categories[5]._id,
                name: "Carlotta Mule",
                price: 1250,
                color: colors[12]._id,
                quantity: 100,
                onSale: true,
                createdAt: "2023-12-27T00:22:53.902Z",
                updatedAt: "2023-12-27T00:22:53.902Z",
            },
            {
                image: "02",
                designer: designers[19]._id,
                category: categories[5]._id,
                name: "Cypher",
                price: 890,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-02-27T00:22:53.902Z",
                updatedAt: "2022-02-27T00:22:53.902Z",
            },
            {
                image: "03",
                designer: designers[13]._id,
                category: categories[5]._id,
                name: "Boy loafer",
                price: 2400,
                color: colors[12]._id,
                quantity: 100,
                onSale: true,
                createdAt: "2022-05-27T00:22:53.902Z",
                updatedAt: "2022-05-27T00:22:53.902Z",
            },
            {
                image: "04",
                designer: designers[13]._id,
                category: categories[5]._id,
                name: "Black loafer",
                price: 3200,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-12-27T00:22:53.902Z",
                updatedAt: "2023-12-27T00:22:53.902Z",
            },
            {
                image: "05",
                designer: designers[19]._id,
                category: categories[5]._id,
                name: "Gipsy",
                price: 760,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-02-27T00:22:53.902Z",
                updatedAt: "2022-02-27T00:22:53.902Z",
            },
            {
                image: "06",
                designer: designers[19]._id,
                category: categories[5]._id,
                name: "Groupie Mule",
                price: 1100,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-05-27T00:22:53.902Z",
                updatedAt: "2022-05-27T00:22:53.902Z",
            },
            {
                image: "07",
                designer: designers[2]._id,
                category: categories[5]._id,
                name: "Storm ankel boot",
                price: 1700,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2023-12-27T00:22:53.902Z",
                updatedAt: "2023-12-27T00:22:53.902Z",
            },
            {
                image: "08",
                designer: designers[22]._id,
                category: categories[5]._id,
                name: "Josefine 100",
                price: 2100,
                color: colors[12]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-02-27T00:22:53.902Z",
                updatedAt: "2022-02-27T00:22:53.902Z",
            },
            {
                image: "09",
                designer: designers[22]._id,
                category: categories[5]._id,
                name: "Josefine 100",
                price: 2100,
                color: colors[13]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-05-27T00:22:53.902Z",
                updatedAt: "2022-05-27T00:22:53.902Z",
            },
            {
                image: "10",
                designer: designers[13]._id,
                category: categories[5]._id,
                name: "Walk'n'Dior high-tops",
                price: 3200,
                color: colors[13]._id,
                quantity: 100,
                onSale: false,
                createdAt: "2022-05-27T00:22:53.902Z",
                updatedAt: "2022-05-27T00:22:53.902Z",
            }
        ])

        console.log('products seeded');

        await User.deleteMany({});

        await User.create({
            firstName: 'Claire',
            lastName: 'Cho',
            email: 'guest@gmail.com',
            password: '1234',
            orders: [
                {
                    products: [products[0]._id, products[0]._id, products[1]._id]
                }
            ]
        });

        console.log('users seeded');

        console.log('Seeding complete!');

        process.exit(0);
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
});